export const ROUTES = {
  home: '/',
  tours: '/tours',
  tourDetail: '/tours/:slug',
  tourSchedules: '/tours/:slug/schedules',
  destinations: '/destinations',
  promotions: '/promotions',
  help: '/help',
  login: '/auth/login',
  register: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  checkout: '/checkout',
  payment: '/checkout/payment',
  paymentSuccess: '/checkout/payment/success',
  paymentFailed: '/checkout/payment/failed',
  accountDashboard: '/account',
  adminDashboard: '/admin',
  forbidden: '/403',
  serverError: '/500',
  public: {
    home: '/',
    tours: '/tours',
    destinations: '/destinations',
    promotions: '/promotions',
    help: '/help',
    tourDetail: '/tours/:id',
    tourSchedules: '/tours/:id/schedules',
  },
  sections: {
    featuredTours: 'featured-tours',
    destinations: 'destinations',
    promotions: 'promotions',
    howItWorks: 'how-it-works',
    bookingConfidence: 'booking-confidence',
    testimonials: 'testimonials',
    finalCta: 'final-cta',
  },
} as const



