# ruff: noqa: E501

DESTINATION_SEEDS = [
    {
        "id": "amalfi-coast",
        "slug": "amalfi-coast",
        "name": "Amalfi Coast",
        "country": "Italy",
        "region": "mediterranean",
        "eyebrow": "Cliffside Escape",
        "summary": "Verified small-group sailings, polished coastal pacing, and postcard anchorages across Southern Italy.",
        "description": "A destination for travelers who want cinematic seascapes, structured downtime, and premium support from harbor to hilltop.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuCUlAAiOeRLsEjWLUpEysDqOn4nFxFXVqfWEJgz5fwyHqHmic30h-cOFQFwH8Dq6uBrAftlcvrZxLiW8IZfq_R_0Sx30G79NJn8II88covl59Q8qQEK6xHy72w9zF7TqOKoCNzYPJN0k8coe80QdWxkfD2t5D86HO_E0zCkESRXjMbo7ZqFEOuo7Mnm7EALBBemW11keI4EPuxpYv6qmsh8enqcucs9hgiw9xmsdOyt4bSTeWmvZIXdEJGziaAz0lRCV9MtFmK9W0-y",
        "imageAlt": "Sunlit Amalfi Coast village with pastel buildings layered above deep blue Mediterranean water.",
        "bestTimeLabel": "Best from May to September",
        "signatureLabel": "Sailing routes and terrace dining",
        "featured": True,
        "tourSearchValue": "Amalfi Coast",
    },
    {
        "id": "cinque-terre",
        "slug": "cinque-terre",
        "name": "Cinque Terre",
        "country": "Italy",
        "region": "mediterranean",
        "eyebrow": "Coastal Trail",
        "summary": "Walkable villages, sea-view paths, and relaxed departures shaped for guests who want light adventure with polish.",
        "description": "Ideal for travelers who want colorful harbors, editorial scenery, and practical logistics instead of rushed stopovers.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuA9YRlTU-fr-mrFCODMLUWJbqd-rbXduL_lPQc_WGguC526SxOAn6XL5BiHrzOqjs2UhcegplxdaWIo4WA90ZYlMoDd82ToK1LWRF9gfoMq8kpKSKj16KimClz8yXO3WV7EwUdl40DDCFQC4EkpwE95cZQgAFGItFQJqYCW9RELScaBuWhmXGE89tTWsIN6ba-pSr70tIZxMTQqSWx3HG1Ihc54stGBgttskGG6PO8ZqGklluBH_b_i1mPCAkLEjXZdC8eFzHkusgDL",
        "imageAlt": "Colorful Cinque Terre cliffside homes overlooking a bright harbor and turquoise water.",
        "bestTimeLabel": "Best from April to October",
        "signatureLabel": "Village trails and harbor stays",
        "featured": False,
        "tourSearchValue": "Cinque Terre",
    },
    {
        "id": "iceland",
        "slug": "iceland",
        "name": "Iceland",
        "country": "Iceland",
        "region": "northern-europe",
        "eyebrow": "Elemental Landscapes",
        "summary": "Published departures combine volcanic scenery, thermal rituals, and reliable road-based planning.",
        "description": "Designed for travelers who want dramatic nature with clear structure, secure operations, and weather-smart pacing.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBsqQZAyEAySTyfrTxwslhrQPCq9YV3XCTuKaXasekBoGKSoR8Jj_FID9LWehqE2F8IWBbFvYiWF3jGJzCF1GZNVbkW8Ep-eIaXXkUNrYbAY4V2VtD9Peqke8qG1042IpwkIyLrwq-ZnqBtKxTKniHccy2KzVOdtEPcc3bip4CY71uxPYzSax3IFfVZFuG26CCaqYm7np4KnBGTvo7NDRX9xZqK45DUks7dUdekFhaoJ1e8bfqrZGGlKuq0kvNn7wdhM-kZ9KNDkLsc",
        "imageAlt": "Powerful Icelandic waterfall cascading over dark cliffs beneath a cool grey sky.",
        "bestTimeLabel": "Best from June to September",
        "signatureLabel": "Waterfalls, geothermal pools, and ring-road scenery",
        "featured": True,
        "tourSearchValue": "Iceland",
    },
    {
        "id": "baltic-capitals",
        "slug": "baltic-capitals",
        "name": "Baltic Capitals",
        "country": "Estonia, Latvia & Lithuania",
        "region": "northern-europe",
        "eyebrow": "Grand City Circuit",
        "summary": "A refined Northern Europe edit with design-led cities, historic cores, and smoother long-haul pacing.",
        "description": "Best for guests who want culture, architecture, and verified logistics across multiple capitals without losing the premium feel.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuByCCGNFooMVDypyWmbFtZ96sQpU-s1iVrvtH8hyHN4lyAjJ6mRITrDtrZzTVg4CKrvcR84ULL8xJWXULTPE5_F0idtPcGhS4kSnPOYJ6m2jlYR9MGJ6oPPclHCgGsoG0yTxZNVeFDnNCNE0p3r93ImC69iZnRoDQ1gaknwxx39BecQpKDHhDtqNS91e7dyBbWJabQRRJjBt_rwheCy4m5mSGcNiZHZWPCcPidOxsV3R8J-svpwQZcgb-TYQuRDiZ8txNKbc1VzrqZH",
        "imageAlt": "Golden cathedral domes and illuminated historic buildings in a Baltic capital at blue hour.",
        "bestTimeLabel": "Best from May to September",
        "signatureLabel": "Historic centers, museums, and boutique hotels",
        "featured": False,
        "tourSearchValue": "Baltic Capitals",
    },
    {
        "id": "kyoto",
        "slug": "kyoto",
        "name": "Kyoto",
        "country": "Japan",
        "region": "asia-pacific",
        "eyebrow": "Temple District",
        "summary": "Slow cultural pacing through temple neighborhoods, heritage streetscapes, and locally guided details.",
        "description": "For travelers who prefer quiet mornings, structured discovery, and an editorial approach to cultural depth.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBdJD4h6Im2zKxOobn5rx1zyrcjL1PY9yyK49sW_JWgJOGhCvx9Y2BRVuwp1u_sLHsPBuVu9XNkUuguU4ycom40O7GZImEJo_e-ggY3R-akbO5MUCtGSKK_BTGt1QEZDhaLtWLH04wiaT2IhfpKJBmC2-lYY8QjLePUExeCqDiy_KGHQsJPmqZxbgDwgqXdfpaCjYgXlZnBtF5ShW0-9-McKkv1_kpSWqZVUGGWjlrDapBTtOC-5gCAzMKCzaSsCHMxBqgvHY4NgJL1",
        "imageAlt": "Traditional Kyoto temple set against misty green mountains and layered roofs.",
        "bestTimeLabel": "Best from March to May",
        "signatureLabel": "Temple districts and heritage lanes",
        "featured": True,
        "tourSearchValue": "Kyoto",
    },
    {
        "id": "bali",
        "slug": "bali",
        "name": "Bali",
        "country": "Indonesia",
        "region": "asia-pacific",
        "eyebrow": "Wellness Journey",
        "summary": "Rice-terrace landscapes, polished wellness pacing, and cultural moments backed by verified local delivery.",
        "description": "A strong fit for travelers who want softness, greenery, and dependable planning without losing atmosphere.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuA4MNyX3YTTYMju_j8GsHYI_rxvRe6dweJFUv-jE3mWicoWPz0TASr28C4ialWZMZxKLjMuj4FdspL7sXEsaojwac7gSjbJkwLyObStt0Jd6wlFJ0iQGlaKrvjfb3xgGl4-dBpnwnTCRMjacXq_SL2h6izdpLmMkPb_5wrvZeTbpaHrSYMfrvNRXNSoM2D2TFwDwyOVgazw7fa693IluqrRFmkNWPXsWiXcVRO4XrZyX_8ODcUvnni7k3O21SAWys2xwnE4mjcxZul9",
        "imageAlt": "Lush Balinese rice terraces in warm morning light with tropical mist in the valley.",
        "bestTimeLabel": "Best from April to October",
        "signatureLabel": "Wellness stays and cultural immersion",
        "featured": True,
        "tourSearchValue": "Bali",
    },
]

PROMOTIONS = [
    {
        "id": "seasonal-coastline-special",
        "category": "seasonal",
        "status": "active",
        "eyebrow": "Seasonal Access",
        "badge": "Complimentary coastal add-on",
        "title": "Seasonal Coastline Special",
        "offerSummary": "Complimentary boat excursion or chef-led tasting on selected seaside departures.",
        "description": "Reserve a qualifying coastline itinerary before the summer window closes and add a signature destination moment without changing the pacing of your trip.",
        "applicableLabel": "Applies to Amalfi Coast, Cinque Terre, and Maldives departures.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuCYr6UoUXza-Rxyx5gz2FLRC6AGpbtwDLzsvIoUfoMgJydSQjyYo5CKHlUeq0AsXMK59_6pWj_RSVJXG3ecpSThDTy3R705lliyFIr9AQsx-peQ4TYWoEJLP185pw67VX3TdHN_X5eD1fj8XWWQMogzGH_CloEjV1cGmWmej-gY_zfWeIPQlf6CblQmwuY_sqdJFUCiwaQ4A7qpcgaitFHNSLS4Z8sF8NnwZJHKKL7MvRwiqtRgPVucxtjnz0Sf5yxBXdhQ5LAW4nG7",
        "imageAlt": "Sun-drenched coastline with mountains falling into a calm turquoise sea.",
        "validFrom": "2026-03-01",
        "validUntil": "2026-06-30",
        "featured": True,
        "primaryCta": {"label": "View Tours", "href": "/tours", "kind": "tours"},
        "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        "banner": {
            "id": "seasonal-coastline-banner",
            "eyebrow": "Featured Promotion",
            "badge": "Seasonal Coastline Special",
            "title": "Travel deeper into the season, with premium moments already built in.",
            "description": "This month’s coastline collection pairs secure departures with editorial extras, from private tastings to water-level experiences that feel tailored rather than tacked on.",
            "status": "active",
            "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuCYr6UoUXza-Rxyx5gz2FLRC6AGpbtwDLzsvIoUfoMgJydSQjyYo5CKHlUeq0AsXMK59_6pWj_RSVJXG3ecpSThDTy3R705lliyFIr9AQsx-peQ4TYWoEJLP185pw67VX3TdHN_X5eD1fj8XWWQMogzGH_CloEjV1cGmWmej-gY_zfWeIPQlf6CblQmwuY_sqdJFUCiwaQ4A7qpcgaitFHNSLS4Z8sF8NnwZJHKKL7MvRwiqtRgPVucxtjnz0Sf5yxBXdhQ5LAW4nG7",
            "imageAlt": "Panoramic luxury coastline with dramatic cliffs and clear water.",
            "validFrom": "2026-03-01",
            "validUntil": "2026-06-30",
            "highlights": [
                "Complimentary destination moment for confirmed coastal bookings.",
                "Priority inventory on editorial seaside itineraries.",
                "Direct CTA into tours or schedule selection.",
            ],
            "primaryCta": {"label": "Explore Eligible Tours", "href": "/tours", "kind": "tours"},
            "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        },
    },
    {
        "id": "early-booking-confidence",
        "category": "early_booking",
        "status": "limited",
        "eyebrow": "Locked-In Planning",
        "badge": "Best 90+ days out",
        "title": "Early Booking Confidence",
        "offerSummary": "Secure rate stability and a softer reschedule path on selected alpine and long-haul departures.",
        "description": "Designed for travelers who want premium inventory before it tightens, this offer protects lead-time decisions with concierge support and verified operator scheduling.",
        "applicableLabel": "Best fit for Switzerland, Iceland, and Baltic departures.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBBNSc_YFPUABETMaXSaaUKh1lfKsvZEk_KcVnGwwAqEUu7CTWA0XHmbILCJdkk9HFB4kDvEdFRLFgXxZ5vSREeeyT-Lp5a60Bx9rM1_LpE1EP5D9Aw7PjG0-MpouAIDoR4CI-rsq6ep4QAyuJaU-A3SwYg1XTNZ-aarMcDR-hG21N8Sy9rfNlKxJe0pJbXXrQvXu2z72fx6GHDTw4i-6m7_sBLPpjHi-CZYIrb9397miPFRlZrK-kAquszhUh4FSXdO7UxEp1l74VQ",
        "imageAlt": "Sharp alpine ridges rising above a moody blue horizon.",
        "validFrom": "2026-03-15",
        "validUntil": "2026-09-15",
        "featured": True,
        "primaryCta": {"label": "View Tours", "href": "/tours", "kind": "tours"},
        "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        "banner": {
            "id": "early-booking-banner",
            "eyebrow": "Limited Window",
            "badge": "Early Booking Confidence",
            "title": "Hold the best departures while the calendar is still generous.",
            "description": "For a short booking window, selected early reservations include locked-in positioning on premium departures and clearer flexibility if dates need to move.",
            "status": "limited",
            "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBBNSc_YFPUABETMaXSaaUKh1lfKsvZEk_KcVnGwwAqEUu7CTWA0XHmbILCJdkk9HFB4kDvEdFRLFgXxZ5vSREeeyT-Lp5a60Bx9rM1_LpE1EP5D9Aw7PjG0-MpouAIDoR4CI-rsq6ep4QAyuJaU-A3SwYg1XTNZ-aarMcDR-hG21N8Sy9rfNlKxJe0pJbXXrQvXu2z72fx6GHDTw4i-6m7_sBLPpjHi-CZYIrb9397miPFRlZrK-kAquszhUh4FSXdO7UxEp1l74VQ",
            "imageAlt": "Dramatic alpine summit in cool light.",
            "validFrom": "2026-03-15",
            "validUntil": "2026-09-15",
            "highlights": [
                "Ideal for 90+ day booking lead times.",
                "Limited allocations on high-demand departures.",
                "Concierge-assisted schedule changes where eligible.",
            ],
            "primaryCta": {"label": "Review Eligible Departures", "href": "/tours", "kind": "tours"},
            "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        },
    },
    {
        "id": "private-departure-edit",
        "category": "private_departure",
        "status": "active",
        "eyebrow": "Private Departure",
        "badge": "Concierge rooming support",
        "title": "Private Departure Edit",
        "offerSummary": "Smaller groups unlock tailored pacing, airport coordination, and elevated arrival support.",
        "description": "For travelers booking a private departure or family-led departure, the operations team can shape rooming, transfers, and milestone moments around a single planning thread.",
        "applicableLabel": "Available for selected Vietnam, Bali, and Kyoto departures.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuA4MNyX3YTTYMju_j8GsHYI_rxvRe6dweJFUv-jE3mWicoWPz0TASr28C4ialWZMZxKLjMuj4FdspL7sXEsaojwac7gSjbJkwLyObStt0Jd6wlFJ0iQGlaKrvjfb3xgGl4-dBpnwnTCRMjacXq_SL2h6izdpLmMkPb_5wrvZeTbpaHrSYMfrvNRXNSoM2D2TFwDwyOVgazw7fa693IluqrRFmkNWPXsWiXcVRO4XrZyX_8ODcUvnni7k3O21SAWys2xwnE4mjcxZul9",
        "imageAlt": "Layered tropical terraces and a quiet villa landscape in Bali.",
        "validFrom": "2026-02-20",
        "validUntil": "2026-12-31",
        "featured": False,
        "primaryCta": {"label": "View Tours", "href": "/tours", "kind": "tours"},
        "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        "banner": None,
    },
    {
        "id": "group-escape-suite-pairing",
        "category": "group_escape",
        "status": "active",
        "eyebrow": "Group Escape",
        "badge": "Best for 3+ travelers",
        "title": "Suite Pairing for Group Escapes",
        "offerSummary": "Connected room planning and hosted dining credits for celebratory multi-room bookings.",
        "description": "A refined option for groups that want clarity, not compromise. Selected departures include connected room pairing guidance and curated dining touches for shared milestones.",
        "applicableLabel": "Applies to selected Maldives and Baltic group departures.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuA7rbYF68xNNLrAi_sBZZvcxv3Zi1TPNIHTOsmyz18aBcxLii_wMrH-YPrAieTazJVzQDQ0SAk-YIomm_OXno4ofwIB-PkzS5N4olNpz8AW7CM_GCVtAUQdz19UP9SuJIjHl8Xul2xFMMzNV4PF4fokzD_YMAQ9iN3BlBxhLtWNjglpGQWnpi-IcmKh-wtJ4rAheUu5MPmdmHfuBX1Xgz2OSQV8NsrEcdUSrgAwH474TCkA",
        "imageAlt": "Luxury overwater villas in bright blue tropical water.",
        "validFrom": "2026-04-01",
        "validUntil": "2026-08-31",
        "featured": False,
        "primaryCta": {"label": "View Tours", "href": "/tours", "kind": "tours"},
        "secondaryCta": {"label": "Browse Eligible Tours", "href": "/tours", "kind": "booking"},
        "banner": None,
    },
    {
        "id": "winter-desert-concierge",
        "category": "seasonal",
        "status": "expired",
        "eyebrow": "Editorial Archive",
        "badge": "Winter departure archive",
        "title": "Desert Concierge Recovery",
        "offerSummary": "An example of a completed seasonal offer kept visible for transparency and reference.",
        "description": "This previous campaign paired premium desert departures with recovery credits and lounge access. It is now closed, but remains listed to keep promotion status and timing explicit.",
        "applicableLabel": "Expired offer shown for transparency on campaign windows.",
        "imageUrl": "https://lh3.googleusercontent.com/aida-public/AB6AXuBWJnVZ1Y_VDKJuWOa7ByGZxA27sUv-32Bi4yaez01Kh1hBa-jB0teLALrt2wawFOXX9EzzQt1P4xHaeEYomzrO6pMpfj1k_MvlLblA_1EKwvDtc0ESTcaV9lAcBK8YYWcYJ-4MoPmFx6TkZDFGAgU_rz9QwPW8N7c1ifEPEDgnALTHSV1pWmqi0i4XKNLzMLi8lJiIp4fvYSNIL5X_s94GGhkIwtsCpuagDig3k3QgM3b4RQFkzHgfkR46zzdqDMEWoI8LweS9H0We",
        "imageAlt": "Luxury desert camp lit under a deep evening sky.",
        "validFrom": "2025-11-01",
        "validUntil": "2026-01-31",
        "featured": False,
        "primaryCta": {"label": "Explore Current Tours", "href": "/tours", "kind": "tours"},
        "secondaryCta": None,
        "banner": None,
    },
]

SUPPORT_HELP_TOPICS = [
    {
        "id": "bookings",
        "title": "Bookings & schedules",
        "description": "Confirmation windows, departure changes, and schedule clarity before you travel.",
        "iconKey": "calendar",
        "bullets": ["Instant confirmation timing", "Date change requests", "Departure schedule questions"],
        "searchTerms": ["booking", "bookings", "schedule", "departure", "change dates", "confirmation"],
        "ctaLabel": "See booking answers",
    },
    {
        "id": "payments",
        "title": "Payments & security",
        "description": "Payment methods, secure checkout guidance, and billing-related questions.",
        "iconKey": "wallet",
        "bullets": ["Accepted payment methods", "Secure checkout guidance", "Billing and payment verification"],
        "searchTerms": ["payment", "payments", "card", "bank transfer", "wallet", "billing", "security"],
        "ctaLabel": "See payment answers",
    },
    {
        "id": "refunds",
        "title": "Refunds & changes",
        "description": "Cancellation terms, refund review timing, and operator-led changes.",
        "iconKey": "refund",
        "bullets": ["Refund review timelines", "Operator-led itinerary changes", "Cancellation and rebooking options"],
        "searchTerms": ["refund", "refunds", "cancel", "cancellation", "rebook", "change booking"],
        "ctaLabel": "See refund answers",
    },
    {
        "id": "trip-support",
        "title": "Trip support",
        "description": "Urgent travel assistance and follow-up paths for active or upcoming bookings.",
        "iconKey": "ticket",
        "bullets": ["Urgent departure assistance", "Live travel coordination", "Following up on open requests"],
        "searchTerms": ["support", "urgent", "trip", "traveler support", "ticket", "contact support"],
        "ctaLabel": "See support answers",
    },
]

SUPPORT_FAQS = [
    {
        "id": "faq-bookings-1",
        "topicId": "bookings",
        "categoryTitle": "Bookings & schedules",
        "categoryIconKey": "calendar",
        "question": "How quickly will I receive my booking confirmation?",
        "answer": "Most eligible departures are confirmed instantly after payment. If an operator needs a manual seat check, we usually update you within 12 hours.",
    },
    {
        "id": "faq-bookings-2",
        "topicId": "bookings",
        "categoryTitle": "Bookings & schedules",
        "categoryIconKey": "calendar",
        "question": "Can I change my travel dates after I book?",
        "answer": "Date changes depend on the operator and fare conditions. Reach out as early as possible so the team can review alternate departures before fees increase.",
    },
    {
        "id": "faq-payments-1",
        "topicId": "payments",
        "categoryTitle": "Payments & security",
        "categoryIconKey": "wallet",
        "question": "Which payment methods can I use on TravelBook?",
        "answer": "We support major cards, bank transfers for higher-value bookings, and TravelBook wallet credits where available at checkout.",
    },
    {
        "id": "faq-payments-2",
        "topicId": "payments",
        "categoryTitle": "Payments & security",
        "categoryIconKey": "wallet",
        "question": "Is my payment information stored securely?",
        "answer": "Yes. Payment collection follows secure handling practices, and our support team will never ask you to send full card details over email or chat.",
    },
    {
        "id": "faq-refunds-1",
        "topicId": "refunds",
        "categoryTitle": "Refunds & changes",
        "categoryIconKey": "refund",
        "question": "How long does a refund review usually take?",
        "answer": "Most refund requests move from review to final decision within 3 to 5 business days, depending on operator approval and payment provider timing.",
    },
    {
        "id": "faq-refunds-2",
        "topicId": "refunds",
        "categoryTitle": "Refunds & changes",
        "categoryIconKey": "refund",
        "question": "What if the operator changes my departure window?",
        "answer": "If the operator makes a significant schedule change, we will outline your available rebooking or refund options and guide you through the next step.",
    },
    {
        "id": "faq-support-1",
        "topicId": "trip-support",
        "categoryTitle": "Trip support",
        "categoryIconKey": "ticket",
        "question": "When should I contact urgent traveler support?",
        "answer": "Use urgent support for live trip issues such as same-day transfer problems, missed connections, or arrival coordination within 72 hours of departure.",
    },
    {
        "id": "faq-support-2",
        "topicId": "trip-support",
        "categoryTitle": "Trip support",
        "categoryIconKey": "ticket",
        "question": "How do I follow up on an existing support request?",
        "answer": "Signed-in travelers can open their account support area to review ticket history, send replies, and keep every booking conversation in one place.",
    },
]
